# Generated by Django 5.1.4 on 2025-01-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_transaction_price', models.CharField(blank=True, max_length=20, null=True)),
                ('max_price', models.CharField(blank=True, max_length=20, null=True)),
                ('min_price', models.CharField(blank=True, max_length=20, null=True)),
                ('avg_price', models.CharField(blank=True, max_length=20, null=True)),
                ('percentage', models.CharField(blank=True, max_length=20, null=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_profit', models.CharField(max_length=50)),
                ('company_code', models.CharField(max_length=10)),
            ],
        ),
    ]
